
name: Coprocessor (ap, dev) deploy.

on:
  pull_request:
    types: [edited, opened]

env:
  BRANCH: ${{ github.event.pull_request.base.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  tests_coverage:
    needs: lint
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  
  build:
      needs: tests_coverage
      runs-on: ubuntu-latest
      permissions:
        contents: read
        id-token: write
      outputs:
        SUBGRAPH_NAME: ${{ steps.extract_subgraphs.outputs.SUBGRAPH_NAME }}
      steps:
        - name: Extract Subgraph Names from PR
          id: extract_subgraphs
          run: |
            PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
            echo "PR_BODY Content: $PR_BODY"
    
            SUBGRAPH_NAMES=()
            while IFS= read -r line; do
              SUBGRAPH=$(echo "$line" | awk -F'`' '{print $2}' | tr -d '\r')
              if [[ -n "$SUBGRAPH" ]]; then
                SUBGRAPH_NAMES+=("$SUBGRAPH")
              fi
            done < <(echo "$PR_BODY" | grep -i "Subgraph Name:")
    
            # Convert array to space-separated string
            SUBGRAPH_STRING="${SUBGRAPH_NAMES[*]}"
            echo "Extracted SUBGRAPH_NAME: $SUBGRAPH_STRING"
    
            # Store it in GitHub Actions outputs and env
            echo "SUBGRAPH_NAME=$SUBGRAPH_STRING" >> "$GITHUB_OUTPUT"
            echo "SUBGRAPH_NAME=$SUBGRAPH_STRING" >> "$GITHUB_ENV"
    
        # Debugging Outputs
        - run: |
            echo "SUBGRAPH_NAME: ${{ steps.extract_subgraphs.outputs.SUBGRAPH_NAME }}"


  deploy:
      name: Deploy Coprocessor Applications
      runs-on: ubuntu-latest
      needs: build
      permissions:
        contents: read
        id-token: write
      env:
        SUBGRAPH_NAME: ${{ needs.build.outputs.SUBGRAPH_NAME }}
      steps:
        - name: Parse PR Body
          run: |
            PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
            echo "PR_BODY Content: $PR_BODY"
            DEV_AP=$(echo "$PR_BODY" | grep -A 4 "Dev Environment" | grep "AP Region:" | awk -F'`' '{print $2}')
            echo "DEV_AP=$DEV_AP" >> GITHUB_ENV
        - name: Deploy Using Helm
          run: |
            echo "Subgraphs to deploy: $SUBGRAPH_NAME"
        
            # Iterate over each subgraph
            IFS=' ' read -r -a SUBGRAPH_ARRAY <<< "$SUBGRAPH_NAME"
            for SUBGRAPH in "${SUBGRAPH_ARRAY[@]}"; do
              echo "Deploying Subgraph: $SUBGRAPH"
              echo "DEV: AP=$DEV_AP"
              # helm upgrade --install $SUBGRAPH ./helm/$SUBGRAPH \
              #   --namespace=dev \
              #   --set image.tag=latest \
              #   --wait --atomic \
              #   --timeout 10m \
              #   --debug
            done
